export const CATEGORIES = [
  { id: "lead_info",    label: "Lead Information",  icon: "👤", description: "Contact details, scheduling, and lead metadata." },
  { id: "sales",        label: "Sales & Deals",      icon: "💰", description: "Revenue, payments, and invoice tracking." },
  { id: "quickbooks",   label: "QuickBooks",         icon: "💼", description: "Customer, invoice, and estimate sync fields." },
  { id: "integrations", label: "Integrations",       icon: "🔗", description: "HubSpot, Google, SignNow, and external platform IDs." },
  { id: "automation",   label: "Automation",         icon: "⚡", description: "Email, SMS, and pipeline automation fields." },
  { id: "system",       label: "System Fields",      icon: "⚙️", description: "Internal sync IDs and timestamps. Do not expose to users." },
];

export const GROUPS = {
  lead_info: [
    { id: "contact",    label: "Contact Details",  fields: ["first_name","last_name","email","phone","best_contact_method"] },
    { id: "scheduling", label: "Scheduling",        fields: ["follow_up_date","appointment_date","appointment_time"] },
    { id: "location",   label: "Location",          fields: ["property_address","city","owner_occupied"] },
    { id: "lead_meta",  label: "Lead Metadata",     fields: ["status","source","referral_name","assigned_rep","form_type","lead_score","consent","text_opt_in"] },
    { id: "project",    label: "Project Info",      fields: ["project_type","budget_range","start_timeframe","scope_details","main_goals","must_haves","nice_to_haves","design_status","message","notes"] },
  ],
  sales: [
    { id: "revenue",    label: "Revenue",           fields: ["estimated_value","qb_invoice_amount","qb_deposit_amount","qb_payment_received","qb_balance_due"] },
    { id: "payments",   label: "Payments",          fields: ["qb_payment_status","qb_payment_method","qb_payment_date","qb_payment_notes"] },
    { id: "invoices",   label: "Invoice Settings",  fields: ["qb_invoice_status","qb_invoice_url","qb_invoice_id","qb_invoice_number","qb_invoice_created_date"] },
  ],
  quickbooks: [
    { id: "qb_customer",  label: "Customer Sync",   fields: ["qb_last_sync_at","qb_last_sync_result","qb_last_error","qb_sync_ineligible"] },
    { id: "qb_invoice2",  label: "Invoice Sync",    fields: ["qb_invoice_id","qb_invoice_number","qb_invoice_amount","qb_invoice_status","qb_invoice_url","qb_invoice_created_date"] },
    { id: "qb_payments2", label: "Payment Sync",    fields: ["qb_payment_status","qb_payment_received","qb_deposit_amount","qb_balance_due","qb_payment_method","qb_payment_date"] },
  ],
  integrations: [
    { id: "hubspot",    label: "HubSpot",           fields: ["hubspot_id","hubspot_sync_status","hubspot_last_synced_at","hubspot_sync_error"] },
    { id: "google",     label: "Google",            fields: ["google_contact_id","google_event_id","google_contact_sync_status","google_calendar_sync_status","last_google_sync"] },
    { id: "signnow",    label: "SignNow",           fields: ["signnow_document_id","signnow_status"] },
  ],
  automation: [
    { id: "email_auto",    label: "Email Automation",  fields: [] },
    { id: "sms_auto",      label: "SMS Automation",    fields: [] },
    { id: "pipeline_auto", label: "Pipeline Triggers",  fields: [] },
  ],
  system: [
    { id: "sys_timestamps", label: "Timestamps",        fields: ["created_date","updated_date","last_google_sync","qb_last_sync_at","hubspot_last_synced_at","hubspot_last_updated_at"] },
    { id: "sys_ids",        label: "Internal IDs",      fields: ["created_by","hubspot_sync_hash","google_contact_resource_name","google_contact_etag"] },
    { id: "sys_errors",     label: "Sync Errors",       fields: ["google_contact_sync_error","google_calendar_sync_error","qb_last_error","hubspot_sync_error","hubspot_authoritative_fields"] },
    { id: "sys_flags",      label: "System Flags",      fields: ["qb_sync_ineligible","duplicate_merged","merge_count","last_merge_date","consent","text_opt_in","owner_occupied","lead_score"] },
  ],
};

export const PROPERTY_TYPES = [
  { value: "text",         label: "Text" },
  { value: "number",       label: "Number" },
  { value: "currency",     label: "Currency" },
  { value: "date",         label: "Date" },
  { value: "dropdown",     label: "Dropdown" },
  { value: "multi_select", label: "Multi-select" },
  { value: "boolean",      label: "Boolean" },
  { value: "user",         label: "User Selector" },
];

export const BUILT_IN_PROPERTIES = [
  // ── Lead Information ────────────────────────────────────────────────────────
  { id: "first_name",        label: "First Name",          category: "lead_info",    type: "text",     required: true,  editable: true,  hidden: false, description: "Lead's first name.", synced: false },
  { id: "last_name",         label: "Last Name",           category: "lead_info",    type: "text",     required: true,  editable: true,  hidden: false, description: "Lead's last name.", synced: false },
  { id: "email",             label: "Email",               category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Primary email address.", synced: true },
  { id: "phone",             label: "Phone",               category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Primary phone number.", synced: true },
  { id: "best_contact_method", label: "Best Contact Method", category: "lead_info", type: "dropdown", required: false, editable: true,  hidden: false, description: "Preferred way to reach this lead.", synced: false },
  { id: "property_address",  label: "Address",             category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Property / job site address.", synced: true },
  { id: "city",              label: "City",                category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "City of the property.", synced: true },
  { id: "owner_occupied",    label: "Owner Occupied",      category: "lead_info",    type: "boolean",  required: false, editable: true,  hidden: false, description: "Whether the property is owner-occupied.", synced: false },
  { id: "source",            label: "Lead Source",         category: "lead_info",    type: "dropdown", required: false, editable: true,  hidden: false, description: "How the lead found you.", synced: true },
  { id: "referral_name",     label: "Referral Name",       category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Name of the person who referred this lead.", synced: false },
  { id: "assigned_rep",      label: "Contact Owner",       category: "lead_info",    type: "user",     required: false, editable: true,  hidden: false, description: "Sales rep assigned to this lead.", synced: true },
  { id: "status",            label: "Lead Status",         category: "lead_info",    type: "dropdown", required: true,  editable: true,  hidden: false, description: "Current stage in the sales pipeline.", synced: true },
  { id: "follow_up_date",    label: "Follow-up Date",      category: "lead_info",    type: "date",     required: false, editable: true,  hidden: false, description: "Next scheduled follow-up.", synced: false },
  { id: "appointment_date",  label: "Appointment Date",    category: "lead_info",    type: "date",     required: false, editable: true,  hidden: false, description: "Scheduled appointment date.", synced: true },
  { id: "appointment_time",  label: "Appointment Time",    category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Time of the scheduled appointment.", synced: false },
  { id: "project_type",      label: "Job Type",            category: "lead_info",    type: "dropdown", required: false, editable: true,  hidden: false, description: "Type of renovation or construction project.", synced: true },
  { id: "budget_range",      label: "Budget Range",        category: "lead_info",    type: "dropdown", required: false, editable: true,  hidden: false, description: "Estimated budget range provided by lead.", synced: false },
  { id: "start_timeframe",   label: "Start Timeframe",     category: "lead_info",    type: "dropdown", required: false, editable: true,  hidden: false, description: "When the lead wants to start.", synced: false },
  { id: "scope_details",     label: "Scope Details",       category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Detailed description of project scope.", synced: false },
  { id: "main_goals",        label: "Main Goals",          category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Primary goals the client wants to achieve.", synced: false },
  { id: "must_haves",        label: "Must-Have Items",     category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Non-negotiable items for the project.", synced: false },
  { id: "nice_to_haves",     label: "Nice-to-Have Items",  category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Desired but optional project items.", synced: false },
  { id: "design_status",     label: "Design Status",       category: "lead_info",    type: "dropdown", required: false, editable: true,  hidden: false, description: "Current status of design/plans.", synced: false },
  { id: "message",           label: "Lead Message",        category: "lead_info",    type: "text",     required: false, editable: false, hidden: false, description: "Original message submitted by the lead.", synced: false },
  { id: "notes",             label: "Internal Notes",      category: "lead_info",    type: "text",     required: false, editable: true,  hidden: false, description: "Private notes visible only to the team.", synced: false },
  { id: "form_type",         label: "Form Type",           category: "lead_info",    type: "dropdown", required: false, editable: false, hidden: false, description: "Which form the lead came from.", synced: false },
  { id: "lead_score",        label: "Lead Score",          category: "lead_info",    type: "number",   required: false, editable: false, hidden: false, description: "Calculated lead quality score.", synced: false },
  { id: "consent",           label: "Consent Given",       category: "lead_info",    type: "boolean",  required: false, editable: false, hidden: false, description: "Whether the lead gave marketing consent.", synced: false },
  { id: "text_opt_in",       label: "Text Opt-in",         category: "lead_info",    type: "boolean",  required: false, editable: false, hidden: false, description: "Whether the lead opted into text messages.", synced: false },

  // ── Sales & Deals ───────────────────────────────────────────────────────────
  { id: "estimated_value",   label: "Project Value",       category: "sales",        type: "currency", required: false, editable: true,  hidden: false, description: "Estimated contract value for this project.", synced: false },
  { id: "qb_deposit_amount", label: "Deposit Amount",      category: "sales",        type: "currency", required: false, editable: true,  hidden: false, description: "Deposit amount collected from customer.", synced: true },
  { id: "qb_payment_received", label: "Payment Received",  category: "sales",        type: "currency", required: false, editable: true,  hidden: false, description: "Total payments received to date.", synced: true },
  { id: "qb_balance_due",    label: "Balance Due",         category: "sales",        type: "currency", required: false, editable: false, hidden: false, description: "Remaining balance owed by customer.", synced: true },
  { id: "qb_payment_status", label: "Payment Status",      category: "sales",        type: "dropdown", required: false, editable: true,  hidden: false, description: "Current payment status (unpaid, partial, paid).", synced: true },
  { id: "qb_invoice_status", label: "Invoice Status",      category: "sales",        type: "dropdown", required: false, editable: false, hidden: false, description: "Status of the QuickBooks invoice.", synced: true },
  { id: "qb_payment_method", label: "Payment Method",      category: "sales",        type: "dropdown", required: false, editable: true,  hidden: false, description: "How the customer is paying.", synced: false },
  { id: "qb_payment_date",   label: "Payment Date",        category: "sales",        type: "date",     required: false, editable: true,  hidden: false, description: "Date payment was received.", synced: false },
  { id: "qb_payment_notes",  label: "Payment Notes",       category: "sales",        type: "text",     required: false, editable: true,  hidden: false, description: "Notes about the payment.", synced: false },
  { id: "qb_invoice_amount", label: "Invoice Amount",      category: "sales",        type: "currency", required: false, editable: false, hidden: false, description: "Amount on the QuickBooks invoice.", synced: true },
  { id: "qb_invoice_url",    label: "QB Invoice URL",      category: "sales",        type: "text",     required: false, editable: false, hidden: false, description: "Link to the invoice in QuickBooks.", synced: true },
  { id: "qb_invoice_id",     label: "QB Invoice ID",       category: "sales",        type: "text",     required: false, editable: false, hidden: false, description: "QuickBooks invoice record ID.", synced: true },
  { id: "qb_invoice_number", label: "QB Invoice Number",   category: "sales",        type: "text",     required: false, editable: false, hidden: false, description: "Human-readable invoice number from QB.", synced: true },
  { id: "qb_invoice_created_date", label: "Invoice Created Date", category: "sales", type: "date",    required: false, editable: false, hidden: false, description: "Date the invoice was created in QuickBooks.", synced: true },

  // ── QuickBooks ──────────────────────────────────────────────────────────────
  { id: "qb_last_sync_at",         label: "Last QB Sync",         category: "quickbooks", type: "date",     required: false, editable: false, hidden: false, description: "When this record was last synced with QuickBooks.", synced: true },
  { id: "qb_last_sync_result",     label: "QB Sync Status",       category: "quickbooks", type: "dropdown", required: false, editable: false, hidden: false, description: "Result of the last QuickBooks sync.", synced: true },
  { id: "qb_last_error",           label: "QB Sync Error",        category: "quickbooks", type: "text",     required: false, editable: false, hidden: false, description: "Error message from the last failed QB sync.", synced: true },
  { id: "qb_sync_ineligible",      label: "QB Sync Ineligible",   category: "quickbooks", type: "boolean",  required: false, editable: false, hidden: false, description: "Marks lead as ineligible for QB sync.", synced: true },

  // ── Integrations ────────────────────────────────────────────────────────────
  { id: "hubspot_id",              label: "HubSpot Contact ID",   category: "integrations", type: "text", required: false, editable: false, hidden: false, description: "ID of the contact record in HubSpot.", synced: true },
  { id: "hubspot_sync_status",     label: "HubSpot Sync Status",  category: "integrations", type: "dropdown", required: false, editable: false, hidden: false, description: "Whether this lead is synced to HubSpot.", synced: true },
  { id: "hubspot_last_synced_at",  label: "HubSpot Last Synced",  category: "integrations", type: "date", required: false, editable: false, hidden: false, description: "Last time this lead was synced to HubSpot.", synced: true },
  { id: "hubspot_sync_error",      label: "HubSpot Sync Error",   category: "integrations", type: "text", required: false, editable: false, hidden: false, description: "Error from the last HubSpot sync attempt.", synced: true },
  { id: "google_contact_id",       label: "Google Contact ID",    category: "integrations", type: "text", required: false, editable: false, hidden: false, description: "ID of the linked Google Contact.", synced: true },
  { id: "google_event_id",         label: "Google Calendar Event",category: "integrations", type: "text", required: false, editable: false, hidden: false, description: "ID of the linked Google Calendar event.", synced: true },
  { id: "google_contact_sync_status", label: "Google Contact Sync Status", category: "integrations", type: "dropdown", required: false, editable: false, hidden: false, description: "Sync status with Google Contacts.", synced: true },
  { id: "google_calendar_sync_status", label: "Google Calendar Sync Status", category: "integrations", type: "dropdown", required: false, editable: false, hidden: false, description: "Sync status with Google Calendar.", synced: true },
  { id: "last_google_sync",        label: "Last Google Sync",     category: "integrations", type: "date", required: false, editable: false, hidden: false, description: "Timestamp of last Google sync operation.", synced: true },
  { id: "signnow_document_id",     label: "SignNow Document ID",  category: "integrations", type: "text", required: false, editable: false, hidden: false, description: "ID of the document sent via SignNow.", synced: true },
  { id: "signnow_status",          label: "SignNow Status",       category: "integrations", type: "dropdown", required: false, editable: false, hidden: false, description: "Current signature status from SignNow.", synced: true },

  // ── System Fields ────────────────────────────────────────────────────────────
  { id: "created_date",                 label: "Created At",              category: "system", type: "date",    required: false, editable: false, hidden: true, description: "When this lead was created in the system.", synced: false, isSystem: true },
  { id: "updated_date",                 label: "Updated At",              category: "system", type: "date",    required: false, editable: false, hidden: true, description: "When this lead was last updated.", synced: false, isSystem: true },
  { id: "created_by",                   label: "Created By",              category: "system", type: "text",    required: false, editable: false, hidden: true, description: "User who created this lead.", synced: false, isSystem: true },
  { id: "hubspot_sync_hash",            label: "HubSpot Sync Hash",       category: "system", type: "text",    required: false, editable: false, hidden: true, description: "Internal hash for detecting HubSpot changes.", synced: false, isSystem: true },
  { id: "hubspot_last_updated_at",      label: "HubSpot Last Updated At", category: "system", type: "date",    required: false, editable: false, hidden: true, description: "Timestamp of last HubSpot-side update.", synced: false, isSystem: true },
  { id: "hubspot_authoritative_fields", label: "HubSpot Authoritative Fields", category: "system", type: "text", required: false, editable: false, hidden: true, description: "Fields owned by HubSpot.", synced: false, isSystem: true },
  { id: "google_contact_resource_name", label: "Google Contact Resource", category: "system", type: "text",    required: false, editable: false, hidden: true, description: "Internal Google resource name for contact sync.", synced: false, isSystem: true },
  { id: "google_contact_etag",          label: "Google Contact ETag",     category: "system", type: "text",    required: false, editable: false, hidden: true, description: "ETag for Google Contact sync versioning.", synced: false, isSystem: true },
  { id: "google_contact_sync_error",    label: "Google Contact Sync Error", category: "system", type: "text",  required: false, editable: false, hidden: true, description: "Error from Google Contact sync.", synced: false, isSystem: true },
  { id: "google_calendar_sync_error",   label: "Google Calendar Sync Error", category: "system", type: "text", required: false, editable: false, hidden: true, description: "Error from Google Calendar sync.", synced: false, isSystem: true },
  { id: "duplicate_merged",             label: "Duplicate Merged",        category: "system", type: "boolean", required: false, editable: false, hidden: true, description: "Indicates a duplicate was merged into this record.", synced: false, isSystem: true },
  { id: "merge_count",                  label: "Merge Count",             category: "system", type: "number",  required: false, editable: false, hidden: true, description: "Number of duplicates merged.", synced: false, isSystem: true },
  { id: "last_merge_date",              label: "Last Merge Date",         category: "system", type: "date",    required: false, editable: false, hidden: true, description: "When the last merge occurred.", synced: false, isSystem: true },
];